# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build
    - run: |
       MW_VERSION=$(grep "^version" gradle.properties | sed "s/.*=//" | sed "s/ //g")
       echo "MW_VERSION=${MW_VERSION}" >> $GITHUB_ENV
    - name: Upload .zip
      uses: actions/upload-artifact@v2
      with:
        name: MuWire-${{ env.MW_VERSION }}-${{ github.sha }}
        path: gui/build/distributions/MuWire-${{ env.MW_VERSION }}.zip
